import { CONFIG } from './config.js';
import { ENEMY_TYPES } from './data/enemies.js';
import { SKILLS } from './data/skills.js';
import { rollItem, RARITIES } from './systems/LootSystem.js';
import { InputManager } from './input/InputManager.js';

const TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),rand=(a,b)=>a+Math.random()*(b-a);

export class Game{
  constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.input=new InputManager(canvas);this.last=performance.now();this.camera={x:0,y:0,shake:0};this.projectiles=[];this.enemies=[];this.drops=[];this.particles=[];this.damageTexts=[];this.wave=1;this.stage=1;this.paused=false;this.time=0;this.ember=Number(localStorage.getItem('riftforged_ember')||0);this.setupUI();this.resize();addEventListener('resize',()=>this.resize());this.reset();requestAnimationFrame(t=>this.loop(t));}
  setupUI(){
    this.ui={hpBar:document.querySelector('#hpBar'),hpText:document.querySelector('#hpText'),xpBar:document.querySelector('#xpBar'),xpText:document.querySelector('#xpText'),zone:document.querySelector('#zoneLabel'),dps:document.querySelector('#dpsChip'),crit:document.querySelector('#critChip'),ember:document.querySelector('#emberChip'),feed:document.querySelector('#lootFeed'),choice:document.querySelector('#choiceOverlay'),choiceCards:document.querySelector('#choiceCards'),choiceEyebrow:document.querySelector('#choiceEyebrow'),choiceTitle:document.querySelector('#choiceTitle'),inv:document.querySelector('#inventoryOverlay'),equip:document.querySelector('#equipmentGrid'),death:document.querySelector('#deathOverlay'),deathStats:document.querySelector('#deathStats')};
    document.querySelector('#inventoryButton').onclick=()=>this.toggleInventory();document.querySelector('#closeInventory').onclick=()=>this.toggleInventory(false);document.querySelector('#restartButton').onclick=()=>this.reset();addEventListener('keydown',e=>{if(e.code==='KeyI')this.toggleInventory()});
    setTimeout(()=>document.querySelector('#startHint')?.style.setProperty('opacity','0'),5000);
  }
  resize(){const dpr=Math.min(devicePixelRatio||1,2);this.canvas.width=Math.floor(innerWidth*dpr);this.canvas.height=Math.floor(innerHeight*dpr);this.canvas.style.width=innerWidth+'px';this.canvas.style.height=innerHeight+'px';this.ctx.setTransform(dpr,0,0,dpr,0,0);this.view={w:innerWidth,h:innerHeight,dpr};}
  reset(){this.player={x:CONFIG.world.width/2,y:CONFIG.world.height/2,radius:18,hp:120,maxHp:120,speed:260,damage:22,attackRate:.38,attackTimer:0,projectileSpeed:760,projectiles:1,pierce:0,crit:.05,pickupRadius:90,dashSpeed:750,dashDuration:.15,dashCooldown:1.1,dashTimer:0,dashCd:0,dashDir:{x:0,y:0},leech:0,level:1,xp:0,xpNeed:55,inventory:[],kills:0};this.wave=1;this.stage=1;this.enemies=[];this.projectiles=[];this.drops=[];this.particles=[];this.paused=false;this.ui.death.classList.add('hidden');this.spawnWave();this.updateUI();}
  loop(now){const dt=Math.min(.033,(now-this.last)/1000||0);this.last=now;if(!this.paused){this.time+=dt;this.update(dt);}this.draw();requestAnimationFrame(t=>this.loop(t));}
  spawnWave(){const boss=this.wave%CONFIG.waves.bossEvery===0;const count=boss?1:CONFIG.waves.baseCount+Math.floor((this.wave-1)*1.7);if(boss)this.spawnEnemy('herald',true);else for(let i=0;i<count;i++){const r=Math.random();this.spawnEnemy(this.wave>2&&r>.82?'brute':r>.48?'skitter':'husk');}this.ui.zone.textContent=`裂隙 ${['I','II','III','IV','V'][Math.min(4,this.stage-1)]} · 第 ${this.wave} 波${boss?' · 首領':''}`;}
  spawnEnemy(type,boss=false){const t=ENEMY_TYPES[type],ang=Math.random()*TAU,d=rand(420,780),scale=1+(this.wave-1)*.11;this.enemies.push({type,x:clamp(this.player.x+Math.cos(ang)*d,60,CONFIG.world.width-60),y:clamp(this.player.y+Math.sin(ang)*d,60,CONFIG.world.height-60),hp:t.hp*scale,maxHp:t.hp*scale,speed:t.speed*(1+Math.min(.25,this.wave*.015)),radius:t.radius,damage:t.damage*(1+(this.wave-1)*.08),attackRange:t.attackRange,windup:t.windup,cooldown:t.cooldown,xp:t.xp,state:'chase',timer:0,color:t.color,boss});}
  update(dt){const p=this.player,m=this.input.movement();p.attackTimer-=dt;p.dashCd=Math.max(0,p.dashCd-dt);
    if(this.input.consumeDash()&&p.dashCd<=0&&(m.x||m.y)){p.dashTimer=p.dashDuration;p.dashCd=p.dashCooldown;p.dashDir={...m};this.camera.shake=4;}
    if(p.dashTimer>0){p.dashTimer-=dt;p.x+=p.dashDir.x*p.dashSpeed*dt;p.y+=p.dashDir.y*p.dashSpeed*dt;this.emitTrail(p.x,p.y,'#d7c98e');}
    else{p.x+=m.x*p.speed*dt;p.y+=m.y*p.speed*dt;}p.x=clamp(p.x,35,CONFIG.world.width-35);p.y=clamp(p.y,35,CONFIG.world.height-35);
    if(this.input.attack||this.input.mouse.down)this.tryAttack();
    this.updateEnemies(dt);this.updateProjectiles(dt);this.updateDrops(dt);this.updateParticles(dt);this.camera.x+=(p.x-this.view.w/2-this.camera.x)*Math.min(1,dt*7);this.camera.y+=(p.y-this.view.h/2-this.camera.y)*Math.min(1,dt*7);this.camera.x=clamp(this.camera.x,0,Math.max(0,CONFIG.world.width-this.view.w));this.camera.y=clamp(this.camera.y,0,Math.max(0,CONFIG.world.height-this.view.h));this.camera.shake*=Math.pow(.02,dt);this.updateUI();}
  tryAttack(){const p=this.player;if(p.attackTimer>0)return;let target=null,best=520;for(const e of this.enemies){if(e.hp<=0)continue;const d=dist(p,e);if(d<best){best=d;target=e;}}if(!target)return;p.attackTimer=p.attackRate;const base=Math.atan2(target.y-p.y,target.x-p.x),spread=.12;for(let i=0;i<p.projectiles;i++){const off=(i-(p.projectiles-1)/2)*spread;this.projectiles.push({x:p.x,y:p.y,vx:Math.cos(base+off)*p.projectileSpeed,vy:Math.sin(base+off)*p.projectileSpeed,radius:5,life:1.25,damage:p.damage,pierce:p.pierce,hit:new Set()});}this.emitBurst(p.x+Math.cos(base)*20,p.y+Math.sin(base)*20,'#f0d792',5,70);}
  updateEnemies(dt){for(const e of this.enemies){if(e.hp<=0)continue;const d=dist(e,this.player);if(e.state==='chase'){if(d<=e.attackRange+this.player.radius){e.state='windup';e.timer=e.windup;}else{const dx=(this.player.x-e.x)/(d||1),dy=(this.player.y-e.y)/(d||1);e.x+=dx*e.speed*dt;e.y+=dy*e.speed*dt;}}
      else if(e.state==='windup'){e.timer-=dt;if(e.timer<=0){if(dist(e,this.player)<=e.attackRange+this.player.radius+12)this.damagePlayer(e.damage);e.state='cooldown';e.timer=e.cooldown;}}
      else if(e.state==='cooldown'){e.timer-=dt;if(e.timer<=0)e.state='chase';}}
  }
  updateProjectiles(dt){for(const q of this.projectiles){q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt;for(const e of this.enemies){if(e.hp<=0||q.hit.has(e))continue;if(Math.hypot(q.x-e.x,q.y-e.y)<q.radius+e.radius){q.hit.add(e);let damage=q.damage,crit=Math.random()<this.player.crit;if(crit)damage*=2;this.hitEnemy(e,damage,crit);if(q.pierce>0)q.pierce--;else q.life=0;break;}}}this.projectiles=this.projectiles.filter(q=>q.life>0&&q.x>0&&q.x<CONFIG.world.width&&q.y>0&&q.y<CONFIG.world.height);}
  hitEnemy(e,damage,crit){e.hp-=damage;this.camera.shake=Math.max(this.camera.shake,crit?7:3);this.damageTexts.push({x:e.x,y:e.y-18,text:`${Math.round(damage)}${crit?'!':''}`,life:.65,crit});this.emitBurst(e.x,e.y,e.color,crit?12:6,crit?180:100);if(this.player.leech)this.player.hp=Math.min(this.player.maxHp,this.player.hp+damage*this.player.leech);if(e.hp<=0)this.killEnemy(e);}
  killEnemy(e){this.player.kills++;this.gainXp(e.xp);if(Math.random()<(e.boss?1:.32)){const item=rollItem(this.player.level,Math.random,e.boss?'legendary':null);this.drops.push({x:e.x,y:e.y,item,t:0});}this.emitBurst(e.x,e.y,e.color,e.boss?35:14,e.boss?250:160);setTimeout(()=>{},0);this.enemies=this.enemies.filter(x=>x!==e);if(this.enemies.length===0){this.paused=true;setTimeout(()=>this.openWaveReward(),400);}}
  damagePlayer(amount){if(this.player.dashTimer>0)return;this.player.hp-=amount;this.camera.shake=10;this.damageTexts.push({x:this.player.x,y:this.player.y-25,text:`-${Math.round(amount)}`,life:.7,crit:false,player:true});if(this.player.hp<=0)this.die();}
  gainXp(x){const p=this.player;p.xp+=x;while(p.xp>=p.xpNeed){p.xp-=p.xpNeed;p.level++;p.xpNeed=Math.round(p.xpNeed*1.32+8);this.paused=true;this.openSkillChoice();break;}}
  updateDrops(dt){for(const d of this.drops){d.t+=dt;const dis=dist(d,this.player);if(dis<this.player.pickupRadius){const s=Math.max(160,650*(1-dis/this.player.pickupRadius));d.x+=(this.player.x-d.x)/(dis||1)*s*dt;d.y+=(this.player.y-d.y)/(dis||1)*s*dt;}if(dis<26){this.collectItem(d.item);d.dead=true;}}this.drops=this.drops.filter(d=>!d.dead);}
  collectItem(item){this.player.inventory.unshift(item);this.toastLoot(item);this.applyItem(item);}
  applyItem(item){for(const [k,v] of Object.entries(item.base))this.applyStat(k,v);for(const a of item.affixes)this.applyStat(a.stat,a.value);}
  applyStat(stat,v){const p=this.player;if(stat==='damage')p.damage+=v;else if(stat==='maxHp'){p.maxHp+=v;p.hp+=v}else if(stat==='crit')p.crit+=v;else if(stat==='attackSpeed')p.attackRate*=1-v;else if(stat==='pickup')p.pickupRadius+=v;}
  toastLoot(item){const n=document.createElement('div');n.className='loot-toast';n.style.setProperty('--rarity',item.color);n.innerHTML=`<b>${RARITIES[item.rarity].name}</b> · ${item.name}`;this.ui.feed.prepend(n);while(this.ui.feed.children.length>5)this.ui.feed.lastElementChild.remove();setTimeout(()=>n.remove(),4200);}
  openSkillChoice(){this.showChoices('裂隙祝福',`等級 ${this.player.level} — 選擇一項強化`,this.pick(SKILLS,3),s=>{s.apply(this.player);this.hideChoices();this.paused=false;});}
  openWaveReward(){const choices=[rollItem(this.player.level),rollItem(this.player.level),rollItem(this.player.level)];this.showChoices('戰利品寶箱',`第 ${this.wave} 波已清除 — 選一件裝備`,choices,item=>{this.collectItem(item);this.hideChoices();this.wave++;if((this.wave-1)%5===0)this.stage++;this.spawnWave();this.paused=false;},true);}
  showChoices(eyebrow,title,choices,onPick,isItem=false){this.ui.choiceEyebrow.textContent=eyebrow;this.ui.choiceTitle.textContent=title;this.ui.choiceCards.innerHTML='';for(const c of choices){const b=document.createElement('button');b.className='choice-card';if(isItem)b.style.borderTop=`2px solid ${c.color}`;b.innerHTML=isItem?`<div class="icon">▣</div><h3 style="color:${c.color}">${c.name}</h3><p>${RARITIES[c.rarity].name} · ${c.slot}<br>${Object.entries(c.base).map(([k,v])=>`${k}: +${v}`).join(' · ')}<br>${c.affixes.map(a=>a.text).join('<br>')||'無額外詞綴'}</p><small>選擇此裝備</small>`:`<div class="icon">${c.icon}</div><h3>${c.name}</h3><p>${c.text}</p><small>選擇此祝福</small>`;b.onclick=()=>onPick(c);this.ui.choiceCards.appendChild(b);}this.ui.choice.classList.remove('hidden');}
  hideChoices(){this.ui.choice.classList.add('hidden');}
  pick(arr,n){return [...arr].sort(()=>Math.random()-.5).slice(0,n);}
  toggleInventory(force){const open=force??this.ui.inv.classList.contains('hidden');if(open){this.renderInventory();this.ui.inv.classList.remove('hidden');this.paused=true}else{this.ui.inv.classList.add('hidden');if(this.ui.choice.classList.contains('hidden')&&this.ui.death.classList.contains('hidden'))this.paused=false;}}
  renderInventory(){this.ui.equip.innerHTML=this.player.inventory.length?'':'<div class="item-card">尚未取得裝備。</div>';for(const item of this.player.inventory){const c=document.createElement('article');c.className='item-card';c.style.setProperty('--rarity',item.color);c.innerHTML=`<strong>${item.name}</strong><div>${RARITIES[item.rarity].name} · ${item.slot}</div><div>${Object.entries(item.base).map(([k,v])=>`${k} +${v}`).join(' · ')}${item.affixes.length?'<br>'+item.affixes.map(a=>a.text).join('<br>'):''}</div>`;this.ui.equip.appendChild(c);}}
  die(){this.paused=true;const gained=Math.max(1,Math.floor(this.wave/2)+Math.floor(this.player.kills/12));this.ember+=gained;localStorage.setItem('riftforged_ember',this.ember);this.ui.deathStats.textContent=`抵達第 ${this.wave} 波 · 擊殺 ${this.player.kills} · 帶回 ${gained} 點餘燼`;this.ui.death.classList.remove('hidden');}
  updateParticles(dt){for(const p of this.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.pow(.1,dt);p.vy*=Math.pow(.1,dt);p.life-=dt}this.particles=this.particles.filter(p=>p.life>0);for(const t of this.damageTexts){t.y-=24*dt;t.life-=dt}this.damageTexts=this.damageTexts.filter(t=>t.life>0);}
  emitBurst(x,y,color,n=8,speed=110){for(let i=0;i<n;i++){const a=Math.random()*TAU,s=rand(speed*.25,speed);this.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rand(.18,.55),max:.55,color,size:rand(2,5)});}}
  emitTrail(x,y,color){if(Math.random()<.55)this.particles.push({x:x+rand(-8,8),y:y+rand(-8,8),vx:0,vy:0,life:.25,max:.25,color,size:rand(3,7)});}
  updateUI(){const p=this.player;this.ui.hpBar.style.width=`${clamp(p.hp/p.maxHp*100,0,100)}%`;this.ui.hpText.textContent=`${Math.ceil(Math.max(0,p.hp))} / ${Math.ceil(p.maxHp)}`;this.ui.xpBar.style.width=`${p.xp/p.xpNeed*100}%`;this.ui.xpText.textContent=`Lv.${p.level} · ${Math.floor(p.xp)} / ${p.xpNeed}`;this.ui.dps.textContent=`傷害 ${Math.round(p.damage)}`;this.ui.crit.textContent=`暴擊 ${Math.round(p.crit*100)}%`;this.ui.ember.textContent=`餘燼 ${this.ember}`;}
  worldToScreen(x,y,shakeX=0,shakeY=0){return{x:x-this.camera.x+shakeX,y:y-this.camera.y+shakeY}}
  draw(){const c=this.ctx,w=this.view.w,h=this.view.h,shakeX=(Math.random()-.5)*this.camera.shake,shakeY=(Math.random()-.5)*this.camera.shake;c.clearRect(0,0,w,h);c.fillStyle='#0e1311';c.fillRect(0,0,w,h);
    c.save();c.translate(-this.camera.x+shakeX,-this.camera.y+shakeY);this.drawWorld(c);for(const d of this.drops)this.drawDrop(c,d);for(const q of this.projectiles){c.beginPath();c.arc(q.x,q.y,q.radius,0,TAU);c.fillStyle='#f0d48c';c.shadowBlur=14;c.shadowColor='#e6b75f';c.fill();c.shadowBlur=0;}for(const e of this.enemies)this.drawEnemy(c,e);this.drawPlayer(c);for(const p of this.particles){c.globalAlpha=clamp(p.life/p.max,0,1);c.fillStyle=p.color;c.fillRect(p.x-p.size/2,p.y-p.size/2,p.size,p.size);}c.globalAlpha=1;for(const t of this.damageTexts){c.globalAlpha=clamp(t.life/.65,0,1);c.textAlign='center';c.font=`${t.crit?'800 20px':'700 15px'} system-ui`;c.fillStyle=t.player?'#e87068':t.crit?'#ffd86a':'#eee2bc';c.fillText(t.text,t.x,t.y);}c.restore();c.globalAlpha=1;this.drawVignette(c,w,h);}
  drawWorld(c){c.fillStyle='#111713';c.fillRect(0,0,CONFIG.world.width,CONFIG.world.height);c.strokeStyle='#1b251f';c.lineWidth=1;for(let x=0;x<CONFIG.world.width;x+=80){c.beginPath();c.moveTo(x,0);c.lineTo(x,CONFIG.world.height);c.stroke()}for(let y=0;y<CONFIG.world.height;y+=80){c.beginPath();c.moveTo(0,y);c.lineTo(CONFIG.world.width,y);c.stroke()}c.strokeStyle='#58604e';c.lineWidth=6;c.strokeRect(18,18,CONFIG.world.width-36,CONFIG.world.height-36);for(let i=0;i<55;i++){const x=(i*311)%CONFIG.world.width,y=(i*173)%CONFIG.world.height;c.fillStyle=i%3?'#182019':'#20251b';c.beginPath();c.arc(x,y,2+(i%4),0,TAU);c.fill();}}
  drawPlayer(c){const p=this.player;c.save();c.translate(p.x,p.y);c.rotate(this.time*.4);c.shadowBlur=22;c.shadowColor='#d6c076';c.strokeStyle='#d8c582';c.lineWidth=3;c.beginPath();for(let i=0;i<6;i++){const a=i/6*TAU,r=i%2?17:22;const x=Math.cos(a)*r,y=Math.sin(a)*r;i?c.lineTo(x,y):c.moveTo(x,y)}c.closePath();c.stroke();c.shadowBlur=0;c.fillStyle='#282d28';c.beginPath();c.arc(0,0,11,0,TAU);c.fill();c.restore();}
  drawEnemy(c,e){c.save();c.translate(e.x,e.y);if(e.state==='windup'){const pulse=1+Math.sin(this.time*28)*.08;c.scale(pulse,pulse);c.strokeStyle='#ff9b72';c.lineWidth=3;c.beginPath();c.arc(0,0,e.radius+9,0,TAU);c.stroke();}c.fillStyle=e.color;c.shadowBlur=e.boss?28:10;c.shadowColor=e.color;c.beginPath();c.arc(0,0,e.radius,0,TAU);c.fill();c.shadowBlur=0;c.fillStyle='#151719';c.beginPath();c.arc(-e.radius*.25,-3,3,0,TAU);c.arc(e.radius*.25,-3,3,0,TAU);c.fill();c.restore();if(e.hp<e.maxHp||e.boss){const w=e.boss?90:42;c.fillStyle='#191c1d';c.fillRect(e.x-w/2,e.y-e.radius-16,w,5);c.fillStyle=e.boss?'#8e67bd':'#b6534b';c.fillRect(e.x-w/2,e.y-e.radius-16,w*clamp(e.hp/e.maxHp,0,1),5);}}
  drawDrop(c,d){const bob=Math.sin(d.t*5)*4;c.save();c.translate(d.x,d.y+bob);c.rotate(d.t*.7);c.shadowBlur=18;c.shadowColor=d.item.color;c.strokeStyle=d.item.color;c.lineWidth=2;c.strokeRect(-8,-8,16,16);c.shadowBlur=0;c.restore();c.textAlign='center';c.font='700 10px system-ui';c.fillStyle=d.item.color;c.fillText(d.item.name,d.x,d.y+26);}
  drawVignette(c,w,h){const g=c.createRadialGradient(w/2,h/2,Math.min(w,h)*.25,w/2,h/2,Math.max(w,h)*.7);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(1,'rgba(0,0,0,.58)');c.fillStyle=g;c.fillRect(0,0,w,h);}
}
