import { GEM_BY_ID, rollGem } from '../data/gems.js';
import { CONFIG } from '../config.js';
import { drawGemVisuals, mountGemUI, renderGemUI, toastGem, updateSkillbar } from '../ui/GemUI.js';

const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
export const DEFAULT_SOCKETS=[{id:'s0',linkGroup:0},{id:'s1',linkGroup:0},{id:'s2',linkGroup:0},{id:'s3',linkGroup:0},{id:'s4',linkGroup:1},{id:'s5',linkGroup:1},{id:'s6',linkGroup:1},{id:'s7',linkGroup:null}];

export function createGemState({starter=true}={}){const sockets=DEFAULT_SOCKETS.map(s=>({...s,gemId:null})),state={sockets,stash:[],activeSocketId:null,selectedGemId:null,selectedStashIndex:null};if(starter){sockets[0].gemId='crimson_bolt';state.activeSocketId='s0';state.stash.push('verdant_chain','crimson_aura');}return state;}
export function installGem(state,socketId,gemId,stashIndex=null){if(!GEM_BY_ID[gemId])return false;const socket=state.sockets.find(s=>s.id===socketId);if(!socket)return false;const fromStash=Number.isInteger(stashIndex)&&stashIndex>=0&&state.stash[stashIndex]===gemId,source=fromStash?null:state.sockets.find(s=>s.gemId===gemId);if(fromStash)state.stash.splice(stashIndex,1);else if(source)source.gemId=null;else{const i=state.stash.indexOf(gemId);if(i>=0)state.stash.splice(i,1);}if(socket.gemId)state.stash.push(socket.gemId);socket.gemId=gemId;if(GEM_BY_ID[gemId].kind==='active')state.activeSocketId=socket.id;return true;}
export function removeGem(state,socketId){const socket=state.sockets.find(s=>s.id===socketId);if(!socket?.gemId)return false;state.stash.push(socket.gemId);socket.gemId=null;if(state.activeSocketId===socketId)state.activeSocketId=state.sockets.find(s=>GEM_BY_ID[s.gemId]?.kind==='active')?.id??null;return true;}

function applyEffect(p,e={}){if(e.damageMultiplier)p.damageMultiplier*=e.damageMultiplier;if(e.attackRateMultiplier)p.attackRateMultiplier*=e.attackRateMultiplier;if(e.projectileSpeedMultiplier)p.projectileSpeedMultiplier*=e.projectileSpeedMultiplier;p.extraProjectiles+=e.extraProjectiles||0;p.extraPierce+=e.extraPierce||0;p.extraChain+=e.extraChain||0;}
export function buildGemLoadout(state){const activeSocket=state.sockets.find(s=>s.id===state.activeSocketId&&GEM_BY_ID[s.gemId]?.kind==='active')||state.sockets.find(s=>GEM_BY_ID[s.gemId]?.kind==='active'),active=activeSocket?GEM_BY_ID[activeSocket.gemId]:null,profile={damageMultiplier:1,attackRateMultiplier:1,projectileSpeedMultiplier:1,extraProjectiles:0,extraPierce:0,extraChain:0,critBonus:0,regenMaxHpPerSecond:0,projectileColor:'#f5dfa2'};if(active?.active){applyEffect(profile,active.active);if(active.active.projectileColor)profile.projectileColor=active.active.projectileColor;}const supports=[];if(activeSocket?.linkGroup!=null)for(const socket of state.sockets){if(socket.id===activeSocket.id||socket.linkGroup!==activeSocket.linkGroup)continue;const gem=GEM_BY_ID[socket.gemId];if(!gem||gem.kind!=='support'||(gem.tags?.length&&!gem.tags.some(tag=>active?.tags?.includes(tag))))continue;supports.push(gem);applyEffect(profile,gem.support);}const auras=[];for(const socket of state.sockets){const gem=GEM_BY_ID[socket.gemId];if(gem?.kind!=='aura')continue;auras.push(gem);if(gem.aura?.attackRateMultiplier)profile.attackRateMultiplier*=gem.aura.attackRateMultiplier;profile.critBonus+=gem.aura?.critBonus||0;profile.regenMaxHpPerSecond+=gem.aura?.regenMaxHpPerSecond||0;}return{active,activeSocket,supports,auras,profile};}

const uiHandlers={install:installGem,remove:removeGem,buildLoadout:buildGemLoadout};
function addGemDrop(game,x,y,gem){game.gemDrops.push({x,y,gemId:gem.id,t:0,pulse:Math.random()*Math.PI*2});}
function updateGemDrops(game,dt){const p=game.player;for(const drop of game.gemDrops){drop.t+=dt;drop.pulse+=dt*4;const d=distance(drop,p);if(d<p.pickupRadius){const s=Math.max(160,650*(1-d/p.pickupRadius));drop.x+=(p.x-drop.x)/(d||1)*s*dt;drop.y+=(p.y-drop.y)/(d||1)*s*dt;}if(d<26){game.gemState.stash.unshift(drop.gemId);toastGem(game,GEM_BY_ID[drop.gemId]);drop.dead=true;renderGemUI(game,uiHandlers);}}game.gemDrops=game.gemDrops.filter(d=>!d.dead);}
function nearestChainTarget(game,from,q,maxRange=260){let best=null,bestD=maxRange;for(const e of game.enemies){if(e.hp<=0||q.hit.has(e))continue;const d=distance(from,e);if(d<bestD){bestD=d;best=e;}}return best;}
function baseAttack(game,p,target,profile){p.attackTimer=p.attackRate*profile.attackRateMultiplier;const total=Math.max(1,p.projectiles+profile.extraProjectiles),base=Math.atan2(target.y-p.y,target.x-p.x),spread=.12,speed=p.projectileSpeed*profile.projectileSpeedMultiplier;for(let i=0;i<total;i++){const off=(i-(total-1)/2)*spread;game.projectiles.push({x:p.x,y:p.y,vx:Math.cos(base+off)*speed,vy:Math.sin(base+off)*speed,speed,radius:5,life:1.25,damage:p.damage*profile.damageMultiplier,pierce:p.pierce+profile.extraPierce,chain:profile.extraChain,hit:new Set(),gemColor:profile.projectileColor});}game.emitBurst(p.x+Math.cos(base)*20,p.y+Math.sin(base)*20,profile.projectileColor,6,80);}

function patchCombat(game){game.tryAttack=function(){const p=this.player;if(p.attackTimer>0)return;const loadout=buildGemLoadout(this.gemState);if(!loadout.active)return;let target=null,best=520;for(const e of this.enemies){if(e.hp<=0)continue;const d=distance(p,e);if(d<best){best=d;target=e;}}if(target)baseAttack(this,p,target,loadout.profile);};game.updateProjectiles=function(dt){const loadout=buildGemLoadout(this.gemState),critChance=Math.min(.9,this.player.crit+loadout.profile.critBonus);for(const q of this.projectiles){q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt;for(const e of this.enemies){if(e.hp<=0||q.hit.has(e))continue;if(Math.hypot(q.x-e.x,q.y-e.y)<q.radius+e.radius){q.hit.add(e);let damage=q.damage,crit=Math.random()<critChance;if(crit)damage*=2;this.hitEnemy(e,damage,crit);if(q.chain>0){const next=nearestChainTarget(this,e,q);if(next){const a=Math.atan2(next.y-e.y,next.x-e.x);q.vx=Math.cos(a)*q.speed;q.vy=Math.sin(a)*q.speed;q.x=e.x;q.y=e.y;q.chain--;q.damage*=.88;continue;}}if(q.pierce>0)q.pierce--;else q.life=0;break;}}}this.projectiles=this.projectiles.filter(q=>q.life>0&&q.x>0&&q.x<CONFIG.world.width&&q.y>0&&q.y<CONFIG.world.height);};}

export function enableGemSystem(game){game.gemState=createGemState();game.gemDrops=[];mountGemUI(game,uiHandlers);const baseReset=game.reset.bind(game);game.reset=function(){baseReset();this.gemState=createGemState();this.gemDrops=[];updateSkillbar(this,buildGemLoadout);renderGemUI(this,uiHandlers);};const baseKill=game.killEnemy.bind(game);game.killEnemy=function(enemy){const x=enemy.x,y=enemy.y,gem=Math.random()<(enemy.boss?.58:.05)?rollGem():null;baseKill(enemy);if(gem)addGemDrop(this,x,y,gem);};const baseDrops=game.updateDrops.bind(game);game.updateDrops=function(dt){baseDrops(dt);updateGemDrops(this,dt);};const baseUpdate=game.update.bind(game);game.update=function(dt){baseUpdate(dt);const p=buildGemLoadout(this.gemState).profile;if(p.regenMaxHpPerSecond)this.player.hp=Math.min(this.player.maxHp,this.player.hp+this.player.maxHp*p.regenMaxHpPerSecond*dt);};const baseDraw=game.draw.bind(game);game.draw=function(){baseDraw();drawGemVisuals(this);};patchCombat(game);return game;}
