import test from 'node:test';
import assert from 'node:assert/strict';
import { buildGemLoadout, createGemState, equipSocketItem, installGem } from '../src/game/systems/GemSystem.js';

test('linked support modifies the selected active gem',()=>{const state=createGemState({starter:false});state.stash.push('crimson_bolt','verdant_chain');installGem(state,'s0','crimson_bolt');installGem(state,'s1','verdant_chain');const loadout=buildGemLoadout(state);assert.equal(loadout.active.id,'crimson_bolt');assert.equal(loadout.supports.length,1);assert.equal(loadout.profile.extraChain,1);});
test('unlinked support does not modify active gem',()=>{const state=createGemState({starter:false,layout:[2,1]});state.stash.push('crimson_bolt','verdant_chain');installGem(state,'s0','crimson_bolt');installGem(state,'s2','verdant_chain');const loadout=buildGemLoadout(state);assert.equal(loadout.supports.length,0);assert.equal(loadout.profile.extraChain,0);});
test('aura works without being linked',()=>{const state=createGemState({starter:false,layout:[2,1]});state.stash.push('crimson_bolt','azure_aura');installGem(state,'s0','crimson_bolt');installGem(state,'s2','azure_aura');const loadout=buildGemLoadout(state);assert.equal(loadout.auras.length,1);assert.equal(loadout.profile.critBonus,.06);});
test('duplicate gems in stash install from the tapped stash entry',()=>{const state=createGemState({starter:false,layout:[2]});state.stash.push('crimson_bolt','crimson_bolt');installGem(state,'s0','crimson_bolt',0);assert.deepEqual(state.stash,['crimson_bolt']);installGem(state,'s1','crimson_bolt',0);assert.equal(state.sockets[0].gemId,'crimson_bolt');assert.equal(state.sockets[1].gemId,'crimson_bolt');assert.equal(state.stash.length,0);});
test('linked burst support adds real splash profile values',()=>{const state=createGemState({starter:false});state.stash.push('crimson_bolt','crimson_burst');installGem(state,'s0','crimson_bolt');installGem(state,'s1','crimson_burst');const {profile}=buildGemLoadout(state);assert.equal(profile.splashRadius,88);assert.equal(profile.splashDamageMultiplier,.45);});
test('linked fork support creates two fork projectiles in the profile',()=>{const state=createGemState({starter:false});state.stash.push('verdant_volley','verdant_fork');installGem(state,'s0','verdant_volley');installGem(state,'s1','verdant_fork');const {profile}=buildGemLoadout(state);assert.equal(profile.forks,2);assert.equal(profile.forkDamageMultiplier,.72);});
test('projectile reach support extends speed and lifetime only when linked',()=>{const linked=createGemState({starter:false});linked.stash.push('azure_lance','azure_reach');installGem(linked,'s0','azure_lance');installGem(linked,'s1','azure_reach');const linkedProfile=buildGemLoadout(linked).profile;assert.ok(linkedProfile.projectileSpeedMultiplier>1.2);assert.equal(linkedProfile.projectileLifetimeMultiplier,1.35);const unlinked=createGemState({starter:false,layout:[2,1]});unlinked.stash.push('azure_lance','azure_reach');installGem(unlinked,'s0','azure_lance');installGem(unlinked,'s2','azure_reach');assert.equal(buildGemLoadout(unlinked).profile.projectileLifetimeMultiplier,1);});
test('equipping socket gear returns installed gems to stash and rebuilds sockets',()=>{const state=createGemState();installGem(state,'s1','verdant_chain',0);installGem(state,'s2','crimson_aura',0);assert.equal(state.stash.length,0);const item={id:'armor-1',name:'測試胸甲',socketLayout:[2,1]};assert.equal(equipSocketItem(state,item),true);assert.equal(state.sockets.length,3);assert.equal(state.socketSourceId,'armor-1');assert.equal(state.activeSocketId,null);assert.deepEqual(new Set(state.stash),new Set(['crimson_bolt','verdant_chain','crimson_aura']));});
test('different link groups on equipment stay mechanically separate',()=>{const state=createGemState({starter:false,layout:[2,2]});state.stash.push('crimson_bolt','verdant_chain','crimson_force');installGem(state,'s0','crimson_bolt');installGem(state,'s1','verdant_chain');installGem(state,'s2','crimson_force');const loadout=buildGemLoadout(state);assert.equal(loadout.supports.length,1);assert.equal(loadout.supports[0].id,'verdant_chain');});
